### PR TITLE
Fix small type in defonce doc

### PR DESCRIPTION
**Pull request by PrestanceDesign**

### CODE REVIEW

**Comment by PrestanceDesign** [comment]
OK I lean English everyday, this is not a typo ! :)

**Comment by jr0cket** [comment]
iff is not a general English word, but actually an abbreviation mostly used in mathematics, especially in the area of logic.  It is part of some computing science literature, but not that universal.

https://en.wikipedia.org/wiki/If_and_only_if

In computing iff is generally regarded to mean "if and only if" an expression is true.  In general English though there are a number of interpretations.

It is very understandable to consider this a typo in the docs, especially if a person is not from a mathematics / logic background.  This specific 'typo' has been raise several times, so many people are not that familiar with the term.

Thanks for caring about improving Clojure though.

**Comment by borkdude** [comment]
@PrestanceDesign Note that Clojure doesn't take PRs from Github, not even for typos. More info: https://clojure.org/dev/dev

**Comment by PrestanceDesign** [comment]
@jr0cket Thx for this elaborated answer !
@borkdude Thx for this information.

**Pull request closed without merging**
