### PR TITLE
step must be positive

### PR DESCRIPTION
**Pull request by kworam**
Infinite loop when step is zero or negative

### CODE REVIEW

**Comment by AeroNotix** [comment]
http://clojure.org/contributing

**Comment by puredanger** [comment]
Hello, this project does not accept pull requests. Patches may be submitted by JIRA and require a signed Clojure Contributor Agreement. See http://clojure.org/contributing for more details.

**Comment by kworam** [comment]
Thanks Alex, I will sign the agreement and resubmit.
 
--------- Original Message --------- Subject: Re: [clojure] step must be positive (#51)

**Comment by trustjalaj** [comment]
will anyone help me understand the project?Facing error while copying on editor

**Comment by sdegutis** [comment]
@puredanger Fwiw, the Jira/CCA thing is a show-stopper for a lot of potential contributors (who know about it and take no action because of it).

**Comment by AeroNotix** [comment]
@sdegutis you will convince them at all. They're old fogies and set in their ways.

**Comment by troessner** [comment]
Too bad, i am actually quite fond of clojure but this hostile attitude of the core developers towards potential contributions is deterring and absolutely ridiculous. Open source done wrong.

**Comment by Gonzih** [comment]
Jira is not so hard. It's just another tool. If you want to contribute it
is not such a big barrier.

**Comment by troessner** [comment]
True. But still, signing an agreement and then collaborating via jira is not exactly inviting. But ok, your project, your rules.

**Comment by Gonzih** [comment]
I agree completely. I'm provably just too used to jira.

**Comment by puredanger** [comment]
Can we please end this thread now and move this conversation elsewhere? You are needlessly spamming everyone that watches this repo.

**Comment by troessner** [comment]
Sure. I (we?) was done already.

**Review by muratkalenderoglu — APPROVED** [review]

**Review by muratkalenderoglu — APPROVED** [review]

**Review by muratkalenderoglu — APPROVED** [review]

**Comment by xingzheone** [comment]
Clojure is great. But it's a big failure to pass GitHub pull request. Clojure's internal code is very bad. We need energetic GitHub contributors urgently. JIRA is very bad

**Pull request closed without merging**
